### ISSUE TITLE
Have the current time in events

### ISSUE THREAD

**Issue by dorianboulch** [HugoCapocci/angular-social-video-player#1]
Hello,
First of all, this project is really great and I'd like to thank you to share it with the community.

I would like to get the current time when an event is raised. For example :

``` javascript
$scope.$on('videoPaused', function(e) {
    var ellapsedTime = e.currentTime;
});
```

I saw in YouTube and Dailymotion docs that we can do this.
For YouTube : player.getCurrentTime()
For Dailymotion : player.currentTime

I don't really know how to implement this, what do you think about it ?

**Comment by HugoCapocci** [comment]
Heelo @dorianboulch sorry but I never see your issue so far xD

that's a nice idea, easy to implement but more like 

```
$scope.$on('videoPaused', function(currentTime) {
    var ellapsedTime = currentTime;
});
```
I just have to send the right parameter to the scope.$emit, I'm gonna try it

**Comment by HugoCapocci** [comment]
@dorianboulch you can update to the latest version (0.2.0) and test the following code

```javascript
$scope.$on('videoPaused', function(event, currentTime) {
    var ellapsedTime = currentTime;
});
```

I close the issue
